export { default as Navbar } from './Navbar'
export { default as Home } from './Home'
export { default as Feed } from './Feed'
export { default as VideosFeed } from './VideosFeed'
export { default as Course } from './Course'
export { default as Sidebar } from './Sidebar'
export { default as SyntaxCode } from './SyntaxCode'